### ISSUE TITLE
One purchases and retaining a record of them.

### ISSUE THREAD

**Issue by awartoft** [zf-fr/zfr-cash#7]
Heya,

Kickass module, but i have a slight issue, i need to provide content that is either available via monthly subscription. Something that zfr-cash already handles perfectly, but it also needs to be available via one time purchases. So i simple need to create an association between a BillableObject and a CustomerObject without using a subscription.

Something tells me the initial answer is going to be PR are welcome, but do you have any suggestions before i look into it ?

**Comment by bakura10** [comment]
Hi!

I'm not sure to understand. What you want is a single charge? ZfrCash is only meant to deal with the recurring stuff.

For one time charge you need to use the createCharge (use zfrstripe as its already a dependency of ZfrCash).

Please tell me the exact use case, I'm a Stripe API expert =).

Envoyé de mon iPhone

**Comment by awartoft** [comment]
Yes, I want a single charge, but i also need to track what products a customer has purchased and give them access to those items.

**Comment by bakura10** [comment]
Hhhm that's not what ZfrCash does then. Maybe we could introduce a new interfaces like RecurringBillableInterface and BillableInterface, and introduce a Charge entity.

But I'm afraid that it will introduce unneeded table for mostly everyone.

I'm not sure to see what kind of abstraction ZfrCash could bring to a single charge actually. There is no web hook to listen to...

I'm not against it, id just like to have a way to be able to NOT generate charge tables if one does not need them (recurring only). Otherwise maybe another module (ZfrBabyCash).
